//! Injects Hive's OSC 133 shell-integration script (see
//! `assets/shell_integration/hive-integration.sh`) into freshly spawned
//! interactive shells, without clobbering the user's own shell config.
//!
//! Only zsh and bash are supported; any other shell (fish, nushell,
//! PowerShell, ...) is left untouched. Windows is unsupported for now, since
//! the injection mechanisms below (`ZDOTDIR`, `--rcfile`) are POSIX shell
//! concepts.
//!
//! - zsh: we point `ZDOTDIR` at a generated directory whose `.zshrc`
//!   immediately restores `ZDOTDIR` to the user's real one, sources the
//!   user's real `.zshrc`, and then sources our integration script.
//! - bash: we invoke bash with `--rcfile <generated rcfile>`, which sources
//!   the user's `~/.bashrc` and then our integration script. This makes the
//!   shell a non-login interactive shell (login-only files like
//!   `~/.bash_profile` are not sourced); this is a known, documented
//!   trade-off of the `--rcfile` mechanism.

use std::{
    fs,
    path::{Path, PathBuf},
    sync::OnceLock,
};

use collections::HashMap;
use task::Shell;

const INTEGRATION_SCRIPT: &str =
    include_str!("../../../assets/shell_integration/hive-integration.sh");

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum SupportedShell {
    Zsh,
    Bash,
}

fn supported_shell(program: &str) -> Option<SupportedShell> {
    let stem = Path::new(program)
        .file_stem()
        .map(|stem| stem.to_string_lossy())
        .unwrap_or_default();
    match stem.as_ref() {
        "zsh" => Some(SupportedShell::Zsh),
        "bash" => Some(SupportedShell::Bash),
        _ => None,
    }
}

/// Wraps a value in single quotes for safe interpolation into a POSIX shell
/// script, escaping any embedded single quotes.
fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// Materializes a static string to `dir/file_name` exactly once per process
/// (the content never changes at runtime), returning the resulting path on
/// every call.
fn materialize_once(
    cell: &'static OnceLock<Result<PathBuf, String>>,
    dir_name: &str,
    file_name: &str,
    contents: &str,
) -> Result<&'static Path, String> {
    cell.get_or_init(|| {
        let dir = std::env::temp_dir().join(dir_name);
        fs::create_dir_all(&dir).map_err(|error| error.to_string())?;
        let path = dir.join(file_name);
        fs::write(&path, contents).map_err(|error| error.to_string())?;
        Ok(path)
    })
    .as_deref()
    .map_err(|error| error.clone())
}

fn integration_script_path() -> Result<&'static Path, String> {
    static SCRIPT_PATH: OnceLock<Result<PathBuf, String>> = OnceLock::new();
    materialize_once(
        &SCRIPT_PATH,
        "hive-shell-integration",
        "hive-integration.sh",
        INTEGRATION_SCRIPT,
    )
}

/// The user's real `ZDOTDIR`, falling back to `$HOME`, as seen by Hive's own
/// process environment (which is what a freshly spawned shell would
/// otherwise default to as well).
fn original_zsh_dotdir() -> Option<PathBuf> {
    std::env::var_os("ZDOTDIR")
        .filter(|value| !value.is_empty())
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
}

fn zsh_zdotdir_path(
    original_zdotdir: &Path,
    integration_script: &Path,
) -> Result<&'static Path, String> {
    static ZDOTDIR_PATH: OnceLock<Result<PathBuf, String>> = OnceLock::new();
    let contents = format!(
        "# Generated by Hive: restores ZDOTDIR to the user's real value, \
         sources the user's real .zshrc, then loads Hive's OSC 133 shell \
         integration. See crates/terminal/src/shell_integration.rs.\n\
         export ZDOTDIR={original_zdotdir}\n\
         if [ -f \"$ZDOTDIR/.zshrc\" ]; then\n\
         \t. \"$ZDOTDIR/.zshrc\"\n\
         fi\n\
         . {integration_script}\n",
        original_zdotdir = shell_quote(&original_zdotdir.to_string_lossy()),
        integration_script = shell_quote(&integration_script.to_string_lossy()),
    );
    materialize_once(&ZDOTDIR_PATH, "hive-zsh-zdotdir", ".zshrc", &contents)
        .map(|zshrc_path| zshrc_path.parent().unwrap_or(zshrc_path))
}

fn bash_rcfile_path(integration_script: &Path) -> Result<&'static Path, String> {
    static RCFILE_PATH: OnceLock<Result<PathBuf, String>> = OnceLock::new();
    let contents = format!(
        "# Generated by Hive: sources the user's ~/.bashrc, then loads \
         Hive's OSC 133 shell integration. Hive invokes bash with \
         --rcfile, which makes this a non-login interactive shell, so \
         login-only files (~/.bash_profile, ~/.profile) are intentionally \
         not sourced here. See crates/terminal/src/shell_integration.rs.\n\
         if [ -n \"$HOME\" ] && [ -f \"$HOME/.bashrc\" ]; then\n\
         \t. \"$HOME/.bashrc\"\n\
         fi\n\
         # Capture any DEBUG trap .bashrc just installed (bash-preexec, \
         # command timers, ...) here, at this file's own source depth, and \
         # hand it to the integration script via an env var: on bash 3.2 \
         # (macOS's system /bin/bash), `trap -p DEBUG` reports nothing when \
         # queried from a file sourced-from-a-sourced-file (which is what \
         # the integration script would otherwise be, since it's sourced \
         # from this already-once-sourced rcfile). No command substitution \
         # is used here either, since forking a subshell while a DEBUG \
         # trap is installed corrupts bash 3.2's trap bookkeeping.\n\
         __hive_debug_trap_capture_file=\"${{TMPDIR:-/tmp}}/hive-debug-trap.$$\"\n\
         trap -p DEBUG >\"$__hive_debug_trap_capture_file\" 2>/dev/null\n\
         IFS= read -r __HIVE_PREV_DEBUG_TRAP < \"$__hive_debug_trap_capture_file\"\n\
         rm -f \"$__hive_debug_trap_capture_file\"\n\
         unset __hive_debug_trap_capture_file\n\
         export __HIVE_PREV_DEBUG_TRAP\n\
         . {integration_script}\n\
         # (Re-)install the DEBUG trap here too, one more time, at this \
         # file's own source depth: on bash 3.2, *replacing* an existing \
         # DEBUG trap from a nested source context (this rcfile sourcing \
         # the integration script) silently fails to take effect, leaving \
         # the old trap permanently active even though the integration \
         # script's own `trap ... DEBUG` line ran without error. Only \
         # needed when __hive_preexec was actually defined (interactive \
         # bash sessions; the integration script no-ops otherwise).\n\
         if typeset -f __hive_preexec >/dev/null 2>&1; then\n\
         \ttrap '__hive_preexec' DEBUG\n\
         fi\n",
        integration_script = shell_quote(&integration_script.to_string_lossy()),
    );
    materialize_once(
        &RCFILE_PATH,
        "hive-bash-rcfile",
        "hive-rcfile.bash",
        &contents,
    )
}

/// Attempts to inject Hive's OSC 133 shell integration for the given shell.
///
/// Mutates `env` in place when the mechanism only needs an environment
/// variable (zsh's `ZDOTDIR`). Returns `Some((program, args))` when the
/// caller must instead override the program/args used to spawn the shell
/// (bash's `--rcfile`, which is appended onto any user-provided arguments).
/// Returns `None` with `env` unchanged for unsupported shells or if
/// materializing the integration files fails (logged, non-fatal).
pub(crate) fn inject(
    shell: &Shell,
    is_windows: bool,
    env: &mut HashMap<String, String>,
) -> Option<(String, Vec<String>)> {
    if is_windows {
        return None;
    }

    let (program, args) = shell.program_and_args();
    let supported_shell = supported_shell(&program)?;

    let script_path = match integration_script_path() {
        Ok(path) => path,
        Err(error) => {
            log::warn!("hive shell integration: failed to materialize script: {error}");
            return None;
        }
    };

    match supported_shell {
        SupportedShell::Zsh => {
            let Some(original_zdotdir) = original_zsh_dotdir() else {
                log::warn!(
                    "hive shell integration: could not determine the user's home directory, skipping"
                );
                return None;
            };
            match zsh_zdotdir_path(&original_zdotdir, script_path) {
                Ok(zdotdir) => {
                    env.insert(
                        "ZDOTDIR".to_string(),
                        zdotdir.to_string_lossy().into_owned(),
                    );
                    None
                }
                Err(error) => {
                    log::warn!("hive shell integration: failed to prepare zsh ZDOTDIR: {error}");
                    None
                }
            }
        }
        SupportedShell::Bash => match bash_rcfile_path(script_path) {
            Ok(rcfile) => {
                let mut new_args = args.to_vec();
                new_args.push("--rcfile".to_string());
                new_args.push(rcfile.to_string_lossy().into_owned());
                Some((program, new_args))
            }
            Err(error) => {
                log::warn!("hive shell integration: failed to prepare bash rcfile: {error}");
                None
            }
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_supported_shells_by_program_basename() {
        assert_eq!(supported_shell("/bin/zsh"), Some(SupportedShell::Zsh));
        assert_eq!(
            supported_shell("/usr/local/bin/bash"),
            Some(SupportedShell::Bash)
        );
        assert_eq!(supported_shell("/bin/fish"), None);
        assert_eq!(supported_shell("/bin/sh"), None);
    }

    #[test]
    fn shell_quote_escapes_single_quotes() {
        assert_eq!(shell_quote("plain"), "'plain'");
        assert_eq!(shell_quote("it's"), r"'it'\''s'");
    }

    #[test]
    fn inject_is_noop_on_windows() {
        let mut env = HashMap::default();
        let result = inject(&Shell::Program("zsh".to_string()), true, &mut env);
        assert!(result.is_none());
        assert!(env.is_empty());
    }

    #[test]
    fn inject_is_noop_for_unsupported_shells() {
        let mut env = HashMap::default();
        let result = inject(&Shell::Program("fish".to_string()), false, &mut env);
        assert!(result.is_none());
        assert!(env.is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn inject_sets_zdotdir_for_zsh() {
        let mut env = HashMap::default();
        let result = inject(&Shell::Program("zsh".to_string()), false, &mut env);
        assert!(result.is_none());
        let zdotdir = env.get("ZDOTDIR").expect("ZDOTDIR should be set");
        assert!(
            fs::metadata(zdotdir).is_ok(),
            "ZDOTDIR should exist on disk"
        );
        assert!(fs::metadata(Path::new(zdotdir).join(".zshrc")).is_ok());
    }

    #[cfg(unix)]
    #[test]
    fn inject_overrides_shell_for_bash() {
        let mut env = HashMap::default();
        let result = inject(&Shell::Program("bash".to_string()), false, &mut env);
        let (program, args) = result.expect("bash injection should override the shell command");
        assert_eq!(program, "bash");
        assert!(args.contains(&"--rcfile".to_string()));
        assert!(env.is_empty());
    }
}
